# Page settings

baseURL = "http://example.org/"
languageCode = "en"
title = ""
theme = "hugo-devresume-theme"
googleAnalytics = "UA-XXXXXXX-Y"






[params]
    author = "CowboySmall"
    description = "DevResume - Bootstrap 4 Resume/CV Template For Software Developers"


    primaryColor = "#9a2a2a"
    textPrimaryColor = "#292929"




    [params.profile]
        enable = true
        name = "Cristian Pachacama"
        tagline = "Mathematical Engineer |  Statistics & Operational Research"
        avatar = "foto_david_circular.png"







    [params.contact]
        enable = true
        location = "Quito - Ecuador"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:#"
        text = "0958873211"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "cdpachacama@datascience.ec"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "#"
        text = "www.datascience.ec/blogs/"







    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "Python | numpy, pandas, TensorFlow, plotly, django, flask"
        [[params.skills.list.items]]
        details = "R | dplyr, ggplot2, plotly, leaflet, shiny, sparklyr"
        [[params.skills.list.items]]
        details = "SQL | PostgreSQL, SQL Server"
        [[params.skills.list.items]]
        details = "Power BI | Tableau | Qlik Sense"
        [[params.skills.list.items]]
        details = "HTML | CSS | LateX "
        
        
        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Effective communication"
        [[params.skills.list.items]]
        details = "Strong problem solver"
        [[params.skills.list.items]]
        details = "Good time management"








    [params.education]
        enable = true

        [[params.education.list]]
        degree = "Mathematical Engineering, Statistics and Operational Research"
        university = "Escuela Politécnica Nacional"
        dates = "Ecuador | 2012 - 2018"
        








    [params.awards]
        enable = true

        [[params.awards.list]]
        name = "Ambassador for Research and Science."
        body = "Research Leap"
        date = "Jul 2018"
        








    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "English"
        level = "Professional"
        [[params.languages.list]]
        name = "Spanish"
        level = "Native"








    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Swimming"
        [[params.interests.list]]
        name = "Photography"
        [[params.interests.list]]
        name = "Travelling"








    [params.summary]
        enable = true
        text = "My main area of study is Statistics and Data Science, my goal is to establish myself as an expert in data science, for this I have tried to complement my studies of Mathematics and statistics with those of the use of different software tools and programming languages.   Initially I focused my efforts on learning programming languages such as R and Python, there I acquired various skills for data treatment, modeling and visualization (handling libraries such as: dplyr, ggplot, plotly, leaflet, rmarkdown, shiny, shiny dashboards , pandas, numpy, TensorFlow). In addition, I acquired skills in tools for Analytics such as Power BI, as well as tools designed for Big Data such as Hadoop.  I am currently developing research on new imputation techniques in the area of Space-Temporal Statistics, as well as Satisfaction Analysis with GLMM’s and mixed distributions."








    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Business Intelligence Analyst"
        dates = "2019 - 2020"
        company = "RECOVER Ecuador"
        details = "In charge of carrying out projects related to Machine Learning and Artificial Intelligence, with the aim of improving processes making them more efficient, as well as generating statistical models for decision-making in operations management."
        [[params.experience.list.items]]
        details = "Creation of Scoring models for segmentation of clients."
        [[params.experience.list.items]]
        details = "Implementation of a conversational chatbot, for customer service."
        

        [[params.experience.list]]
        title = "Project Manager"
        dates = "2017 - 2019"
        company = "Pontificia Universidad Católica del Ecuador "
        details = "Carry out a correct development of activities and projects related to scientific research in the area of Economics, Statistics (and related)."
        [[params.experience.list.items]]
        details = "Creation of GeoRTS, an R package for imputation of missing data in space - time processes. ( [link](https://github.com/InstitutoInvestigacionesEconomicasPUCE/geortsBeta))"
        [[params.experience.list.items]]
        details = "Creation of APP (Shiny) for monitoring Cantonal Price Vulnerability Indicators for Ecuador. ([link](https://iiepuce.shinyapps.io/Vulnerabilidad_Precios/))"

        [[params.experience.list]]
        title = "External Consultant"
        dates = "2017 - present"
        company = "MATH Consultancy"
        details = "Course instructor of: Dynamic and Reproducible Reporting with Rmarkdown - Free Software School, tools for all Data Scientists. ([link](https://github.com/MathConsultoresEcuador/Escuela-de-Software-Libre-EPN-))"

       






    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "Research Project"
        meta = "Escuela Politécnica Nacional | 2017 - 2018"
        tagline = "Research Assistant in project: Forecast and Impact of extreme low levels of streamflow in hydropower plants. ( https://cristianpachacama.shinyapps.io/plataformatscluster/ )"
        
        [[params.projects.list]]
        title = "Project"
        meta = "Escuela Politécnica Nacional (DGIP) |  May 2018"
        tagline = "Machine Learning model for forecasting the risk of failure of students of the EPN University."
        
        [[params.projects.list]]
        title = "Academic Project"
        meta = "Escuela Politécnica Nacional (CLAVEMAT) | Nov 2014"
        tagline = "Tutor in: Calculus, Vector Calculus and Linear Algebra"









    [params.information]
        enable = true

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "2019 ·  <i>Breves consideraciones respecto al plan 'Casa para todos' o la Política Social con fomento Productivo</i> - Apuntes Técnicos, Instituto de Investigaciones Económicas, Pontificia Universidad Católica del Ecuador. ([link](https://www.researchgate.net/publication/333934362_BREVES_CONSIDERACIONES_RESPECTO_AL_PLAN_CASA_PARA_TODOS_O_POLITICA_SOCIAL_CON_FOMENTO_PRODUCTIVO))"
        [[params.information.list.items]]
        details = "2020 · <i>Cluster Analysis of Seasonal Time Series, Modeling streamflows of rivers in Brazil</i> - Escuela Politécnica Nacional. ([link](https://cristianpachacama.shinyapps.io/TesisBorrador/))"
        [[params.information.list.items]]
        details = "2020 · <i>imputeSTS, an R package for imputation of missing data in Seasonal Time Series</i>. ([link](https://github.com/CristianPachacama/imputeSTS))"
        
        [[params.information.list]]
        title = "Interests"
        [[params.information.list.items]]
        details = "<b>Research: </b> Geostatistics, Mixed Models, CUB models, Multidimensional Scaling methods, Time Series models, Cluster Analysis."
        [[params.information.list.items]]
        details = "<b>Work: </b> Application of AI & ML techniques, Big Data and Data Science projects related."








    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/CristianPachacama"
        title = "CristianPachacama"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/cristian-david-pachacama"
        title = "cristian-david-pachacama"
        [[params.social.list]]
        icon = "fab fa-twitter-square"
        url = "//twitter.com/CristianDavidPS"
        title = "@CristianDavidPS"





